// import file "globals.css"
import Image from 'next/image'
import './globals.css'
import Link from "next/link"
//import fontawesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Area Header */}
        <header>
            {/* Area banner */}
            {/* <img src={"../images/logo.png"} alt="Logo UTI" /> */}
            <Image src={"/images/logo.png"} alt="Logo UTI" width={320} height={60}></Image>

            {/* Area Menu */}
            <nav className="mt-5 flex justify-center text-center">
              <Link href={"/"} className="bg-teal-500 hover:bg-teal-700 text-black rounded-full px-5 py-2.5 mr-2 w-52"> Data Mahasiswa </Link>
              <Link href={"/"} className="bg-teal-500 hover:bg-teal-700 text-black rounded-full px-5 py-2.5 ml-2"> Log Data Mahasiswa </Link>
            </nav>

        </header>

        {/* Area conten */}
        <section className='m-5'>
          {children}
        </section>

        {/* Area Footer */}
        <footer className="flex justify-center text-center bg-color1 text-color3-satu-a py-15px">
          copyright &copy; 2024_IndriMaharani
        </footer>
      </body>
    </html>
  )
}
